modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/jamtastic/issues"

[[mods]]
modId = "jamtastic"
version = "${file.jarVersion}"
displayName = "Jamtastic"
displayURL="https://github.com/JamCoreModding/jamtastic"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Make any kind of jam you can think of!
'''

[[dependencies.jamtastic]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jamtastic]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jamtastic]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.jamtastic]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "jamtastic.mixins.json"
